# Generated by Django 4.2.7 on 2023-12-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
