# Generated by Django 5.0 on 2024-01-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_alter_categoria_options_alter_detallepedido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True),
        ),
    ]
